spring:
  #  main:
  #    log-startup-info: false

  datasource:
    url: jdbc:mysql://localhost:3306/employee_perf_review_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true

server:
  error:
    include-stacktrace: never